export const API_ENDPOINTS = {
  AUTH: {
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
    ME: '/auth/me',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
  },
  USERS: {
    ME: '/users/me',
    UPDATE_ME: '/users/me',
    DELETE_ME: '/users/me',
  },
  ADMIN: {
    STATS: '/admin/stats',
    USERS: '/admin/users',
    USER_DETAIL: (userId: string) => `/admin/users/${userId}`,
    USER_STATUS: (userId: string) => `/admin/users/${userId}/status`,
    USER_ROLE: (userId: string) => `/admin/users/${userId}/role`,
    SESSIONS: '/admin/sessions',
    SESSION_DELETE: (sessionId: string) => `/admin/sessions/${sessionId}`,
    ORDERS: '/admin/orders',
    ORDER_DETAIL: (orderId: string) => `/admin/orders/${orderId}`,
    ORDER_STATUS: (orderId: string) => `/admin/orders/${orderId}/status`,
    STOREFRONT_SUMMARY: '/admin/storefront/summary',
    STOREFRONT_CATEGORIES: '/admin/storefront/categories',
    STOREFRONT_CATEGORY: (categoryId: string) => `/admin/storefront/categories/${categoryId}`,
    STOREFRONT_CATEGORY_ORDER: '/admin/storefront/categories/order',
    STOREFRONT_ASSETS: '/admin/storefront/assets',
    STOREFRONT_HOME: '/admin/storefront/home',
    STOREFRONT_HOME_HERO: '/admin/storefront/home/hero',
    STOREFRONT_HOME_HERO_SLIDES: '/admin/storefront/home/hero-slides',
    STOREFRONT_HOME_HERO_SLIDE: (slideId: string) => `/admin/storefront/home/hero-slides/${slideId}`,
    STOREFRONT_HOME_HERO_SLIDE_ORDER: '/admin/storefront/home/hero-slides/order',
    STOREFRONT_HOME_PRODUCT_ROWS: '/admin/storefront/home/product-rows',
    STOREFRONT_HOME_PRODUCT_ROW: (rowId: string) => `/admin/storefront/home/product-rows/${rowId}`,
    STOREFRONT_HOME_PRODUCT_ROW_ORDER: '/admin/storefront/home/product-rows/order',
    STOREFRONT_HOME_PRODUCT_ROW_ITEMS: (rowId: string) => `/admin/storefront/home/product-rows/${rowId}/products`,
    STOREFRONT_HOME_PROMO_BANNERS: '/admin/storefront/home/promo-banners',
    STOREFRONT_HOME_PROMO_BANNER: (bannerId: string) => `/admin/storefront/home/promo-banners/${bannerId}`,
    STOREFRONT_HOME_PROMO_BANNER_ORDER: '/admin/storefront/home/promo-banners/order',
    STOREFRONT_HOME_SERVICE_ITEMS: '/admin/storefront/home/service-items',
    STOREFRONT_HOME_SERVICE_ITEM: (itemId: string) => `/admin/storefront/home/service-items/${itemId}`,
    STOREFRONT_HOME_SERVICE_ITEM_ORDER: '/admin/storefront/home/service-items/order',
    STOREFRONT_HOME_NEWSLETTER: '/admin/storefront/home/newsletter',
    STOREFRONT_PRODUCTS: '/admin/storefront/products',
    STOREFRONT_PRODUCT: (productId: string) => `/admin/storefront/products/${productId}`,
  },
  STOREFRONT: {
    HOME: '/storefront/home',
    PRODUCTS: '/storefront/products',
    PRODUCT_DETAIL: (slug: string) => `/storefront/products/${slug}`,
    FAVORITES: '/storefront/favorites',
    FAVORITE_IDS: '/storefront/favorites/ids',
    FAVORITE_PRODUCT: (productSlug: string) => `/storefront/favorites/${productSlug}`,
    CART: '/storefront/cart',
    CART_ITEMS: '/storefront/cart/items',
    CART_ITEM: (itemId: string) => `/storefront/cart/items/${itemId}`,
    CART_PROMO: '/storefront/cart/promo',
    ORDERS: '/storefront/orders',
  },
} as const;
