export const ROUTES = {
  HOME: '/',
  BLOG: '/blog',
  PRODUCTS: '/products',
  PRODUCT_DETAIL: (slug: string) => `/products/${slug}`,
  CART: '/cart',
  ORDER_SUCCESS: (orderCode: string) => `/order-success/${orderCode}`,
  ABOUT_US: '/about-us',
  DELIVERY: '/delivery',
  WARRANTY: '/warranty',
  CONTACT: '/contact',
  PAYMENT_METHODS: '/payment-methods',
  FAQ: '/faq',
  CORPORATE_OFFER: '/corporate-offer',
  LOGIN: '/login',
  REGISTER: '/register',
  VERIFY_ACCOUNT: '/verify-account',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  DASHBOARD_FAVORITES: '/dashboard/favorites',
  DASHBOARD_ORDERS: '/dashboard/orders',
  PROFILE: '/profile',
  ADMIN: {
    DASHBOARD: '/admin',
    HOMEPAGE: '/admin/homepage',
    CATEGORIES: '/admin/categories',
    PRODUCTS: '/admin/products',
    ORDERS: '/admin/orders',
    USERS: '/admin/users',
    USER_DETAIL: (userId: string) => `/admin/users/${userId}`,
    SESSIONS: '/admin/sessions',
  },
} as const;
